reset;

model test2.mod;

data test_20_10.dat;

option cplex_options 'primal mipdisplay=2 mipgap=1e-14';

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_20_20.dat;

option cplex_options 'primal mipdisplay=2 mipgap=1e-14';

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_20_40.dat;

option cplex_options 'primal mipdisplay=2 mipgap=1e-14';

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_20_60.dat;

option cplex_options 'primal mipdisplay=2 mipgap=1e-14';

solve;

display Total_Act, _total_solve_time;
/*reset;

model test2.mod;

data test_20_100.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_40_10.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
/*reset;

model test2.mod;

data test_40_20.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;

reset;

model test2.mod;

data test_40_40.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_40_60.dat;
option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_40_100.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_60_10.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_60_20.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_60_40.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_60_60.dat;
option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_60_100.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_80_10.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_80_20.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_80_40.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_80_60.dat;
option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_80_100.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_100_10.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_100_20.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_100_40.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_100_60.dat;
option solver cplex;

solve;

display Total_Act, _total_solve_time;
reset;

model test2.mod;

data test_100_100.dat;

option solver cplex;

solve;

display Total_Act, _total_solve_time;